### ISSUE TITLE
Extra Bases - Graphics bugs & Game is forced Cocktail mode (dip not working)

### ISSUE THREAD

**Issue by M-Walrus** [MiSTer-devel/Arcade-Astrocade_MiSTer#13]
Graphics glitches when starting game sometimes.  "Insert coin/Press start" text stays in middle of screen after game starts.

Upright/Cocktail Dip switch is broken. Game is cocktail mode no matter what.

**Comment by MacroFPGA** [comment]
It looks as though the upright/cocktail dip switch is ignored by the program.

However, the colour setting also affects the rotation 
- if you select mono, you get black & white screen, but it doesn't rotate.
- if you select colour, you get colour and it does rotate.

so I guess uprights had monochrome screens but cocktails had colour screens.

**Comment by MacroFPGA** [comment]
if you look on https://youtu.be/Wb1hXoFsH8g 

the upright has the monitor reflected off of a 3D background so it only draws the main detail (picture doesn't rotate, so fine for all players)

The cocktail cannot use this, so it instead does shades (on a mono screen, since only intensity and sync are connected) which since we use full rgb comes out in colour.

so we really need a decent picture of a real backdrop for the upright.

**Comment by M-Walrus** [comment]
looks much better with that backdrop in place! that would be a neat addition to this core.

having it force cocktail isnt a huge inconvenience in a game like this, and the controls arent backwards or anything when it flips, so its manageable. would be nice if there were a way to allow two player without it flipping though. multiplayer is the highlight of this game, IMO. anything to make that a better experience is a win in my book.

**Comment by MacroFPGA** [comment]
Now added the backdrop. In all the testing I did I never got corrupted text and it doesn't use SDRAM for that game, so should not be affected by that. 

I also added 2nd player controls to extra bases but not tested them (only have 1 joystick connected up)
